package pzopt;

import gnu.trove.map.hash.TIntObjectHashMap;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import zombie.ZomboidFileSystem;
import zombie.core.Core;
import zombie.core.Translator;
import zombie.gameStates.ChooseGameInfo;
import zombie.iso.IsoWorld;
import zombie.iso.sprite.IsoSprite;
import zombie.iso.sprite.IsoSpriteManager;
import zombie.network.GameClient;
import zombie.network.GameServer;

/**
 * tileDefPreload: the tile definition load of IsoWorld.init (seven .tiles files plus the mods', ~100k sprites with
 * their properties, 0.6 s of the loader thread after Continue) done on a boot thread instead.
 *
 * Stock disposes every sprite at the start of each world load and rebuilds them from the files; the result depends on
 * the files, the loaded mods and the language (moveable display names) only. The boot thread builds them into a
 * private IsoSpriteManager (the global one is used by the menu meanwhile) and creates the sprites without their
 * texture: Texture's shared table is a plain HashMap the main thread fills during boot. install(), called by the
 * loader where stock would start parsing (after stock's Dispose), binds each sprite's texture by its name exactly as
 * IsoSpriteManager.AddSprite does, moves the sprites into the global manager and hands back the tile image list. The
 * property alias table (TilePropertyAliasMap) was generated by the boot thread from the same property strings.
 *
 * One use per boot: a second world load, a changed mod list or language, debug mode or multiplayer take stock's path.
 */
public final class TileDefPreload {
   private static Thread thread;
   private static volatile Throwable failure;
   private static boolean used;
   private static IsoSpriteManager built;
   private static final List<String> tileImages = new ArrayList<>();
   private static List<String> mods;
   private static Object language;
   private static long buildMs;

   private TileDefPreload() {
   }

   private static boolean enabled() {
      return Config.TILE_DEF_PRELOAD && Overrides.enabled() && !Core.debug && !GameServer.server && !GameClient.client;
   }

   /** From GameWindow.enter, once the tile texture packs are registered (the main menu's Lua runs meanwhile). */
   public static synchronized void start() {
      if (thread != null || !enabled()) {
         return;
      }
      mods = new ArrayList<>(ZomboidFileSystem.instance.getModIDs());
      language = Translator.getLanguage();
      List<String> modFiles = new ArrayList<>();
      List<Integer> modNumbers = new ArrayList<>();
      resolveModTileDefs(modFiles, modNumbers);
      IsoWorld world = IsoWorld.instance;
      thread = new Thread(() -> {
         long t0 = System.nanoTime();
         try {
            IsoSpriteManager pm = new IsoSpriteManager();
            world.pzoptPreloadTileDefs(pm, modFiles, modNumbers, tileImages);
            built = pm;
         } catch (Throwable t) {
            failure = t;
         }
         buildMs = (System.nanoTime() - t0) / 1_000_000L;
      }, "pzopt-tiledef-preload");
      thread.setDaemon(true);
      thread.start();
   }

   /** ZomboidFileSystem.loadModTileDefs' file resolution (same order, same duplicate file-number rule, same errors). */
   private static void resolveModTileDefs(List<String> files, List<Integer> numbers) {
      ZomboidFileSystem zfs = ZomboidFileSystem.instance;
      HashSet<Integer> usedFileNumbers = new HashSet<>();
      for (String modId : zfs.getModIDs()) {
         ChooseGameInfo.Mod info = ChooseGameInfo.getAvailableModDetails(modId);
         if (info == null) {
            continue;
         }
         for (ChooseGameInfo.TileDef tileDef : info.getTileDefs()) {
            if (usedFileNumbers.contains(tileDef.fileNumber)) {
               continue;
            }
            String rel = zfs.getRelativeFile("media/" + tileDef.name + ".tiles").toLowerCase(Locale.ENGLISH);
            String path = zfs.activeFileMap.get(rel);
            if (path == null) {
               continue;
            }
            files.add(path);
            numbers.add(tileDef.fileNumber);
            usedFileNumbers.add(tileDef.fileNumber);
         }
      }
   }

   private static List<Map.Entry<String, IsoSprite>> toBind;
   private static int bound;
   private static final int BIND_PER_FRAME = 4000;

   /**
    * From MainScreenState.update (main thread, where binding against the texture table is safe): once the preload is
    * built, bind the textures of the next slice of sprites, so the load finds them bound (~0.1 s of the loader thread
    * otherwise). Same lookups as install(); install() binds what is left.
    */
   public static synchronized void bindSome() { // same lock as install()'s claim: never binds after the loader took the sprites
      Thread t = thread;
      if (t == null || t.isAlive() || used || built == null || failure != null) {
         return;
      }
      if (toBind == null) {
         toBind = new ArrayList<>(built.namedMap.entrySet());
         bound = 0;
      }
      int end = Math.min(toBind.size(), bound + BIND_PER_FRAME);
      for (int i = bound; i < end; i++) {
         Map.Entry<String, IsoSprite> e = toBind.get(i);
         if (!e.getKey().isEmpty()) {
            e.getValue().LoadSingleTexture(e.getKey());
         }
      }
      bound = end;
   }

   /**
    * Move the preloaded sprites into {@code target} (already disposed by the caller) and fill {@code tileImagesOut};
    * false when there is nothing valid to install and the caller must load the tile definitions itself.
    */
   public static boolean install(IsoSpriteManager target, List<String> tileImagesOut) {
      Thread t;
      synchronized (TileDefPreload.class) {
         if (used || thread == null) {
            return false;
         }
         used = true;
         t = thread;
      }
      long w0 = System.nanoTime();
      try {
         t.join();
      } catch (InterruptedException e) {
         Thread.currentThread().interrupt();
         return false;
      }
      long waitedMs = (System.nanoTime() - w0) / 1_000_000L;
      String why = null;
      if (failure != null) {
         why = "failed: " + failure;
      } else if (!mods.equals(ZomboidFileSystem.instance.getModIDs())) {
         why = "mod list changed";
      } else if (language != Translator.getLanguage()) {
         why = "language changed";
      } else if (!enabled()) {
         why = "not applicable";
      }
      if (why != null) {
         Log.info("tile definitions preload not used (" + why + "); loading them as stock");
         built = null;
         return false;
      }
      long b0 = System.nanoTime();
      IsoSpriteManager pm = built;
      built = null;
      int n = 0;
      int boundAtMenu = 0;
      java.util.HashSet<String> done = new java.util.HashSet<>();
      if (toBind != null) {
         for (int i = 0; i < bound; i++) {
            done.add(toBind.get(i).getKey());
         }
         boundAtMenu = bound;
         toBind = null;
      }
      for (Map.Entry<String, IsoSprite> e : pm.namedMap.entrySet()) {
         String name = e.getKey();
         if (name.isEmpty()) {
            continue; // the manager's own empty sprite; the target keeps its own
         }
         IsoSprite spr = e.getValue();
         if (!done.contains(name)) {
            spr.LoadSingleTexture(name); // IsoSpriteManager.AddSprite(name, id) does this first
         }
         target.namedMap.put(name, spr);
         n++;
      }
      TIntObjectHashMap<IsoSprite> ids = pm.intMap;
      ids.forEachEntry((id, spr) -> {
         target.intMap.put(id, spr);
         return true;
      });
      tileImagesOut.addAll(tileImages);
      Log.info(String.format("tile definitions preloaded at boot: %d sprites, built in %d ms, waited %d ms, %d textures bound at the menu, install %d ms",
            n, buildMs, waitedMs, boundAtMenu, (System.nanoTime() - b0) / 1_000_000L));
      return true;
   }

   /**
    * IsoSpriteManager.AddSprite(name, id) without the texture lookup (install() binds it on the loader thread): same
    * duplicate rule (a repeated name keeps the first ID), same maps.
    */
   public static IsoSprite addSprite(IsoSpriteManager mgr, String name, int id) {
      IsoSprite spr = new IsoSprite(mgr);
      IsoSprite existing = mgr.namedMap.get(name);
      if (existing != null) {
         id = existing.id;
      }
      mgr.namedMap.put(name, spr);
      spr.id = id;
      mgr.intMap.put(id, spr);
      return spr;
   }
}
